# **Introdução ao NumPy**

## Introdução

O NumPy é uma biblioteca para tratamento de arrays multidimensionais, com diversas aplicações em cálculo numérico, álgebra linear, Machine Learning e diversas outras funções para programação científica.Sua implementação se baseia na linguagem C, o que proporciona alta performance no tratamento e manipulação de arrays, por meio de diversas funções e operadores. Este notebook objetiva apresentar uma breve introdução ao NumPy. As funções aplicáveis a Àlgebra Linear serão tratadas separadamente em outro notebook.

## Instalação

Inicialmente, é necessário instalar a biblioteca NumPy. Para tanto, para os usuários Windows poderão executar o prompt comando e executar o comando abaixo.

*pip install numpy*

Para usuários Windows a instalação pode ser efetuada pelo Anaconda também:

*conda install numpy*


Para usuários Linux (Ubuntu e Debian): 

*sudo apt-get install python-numpy*

## Importando o NumPy

O primeiro passo é importar a biblioteca NumPy,para tanto podemos usar o comando abaixo:

In [1]:
import numpy as np

Para verificar a versão do NumPy em execução o seguinte comando pode ser utilizado:

In [3]:
np.__version__

'1.19.0'

## Objeto ndarray

O objeto primordial quando trabalhamos com Numpy é o ndarray (classe). Ou seja, ao criar um array com esta biblioteca estamos instanciando objetos da classe ndarray, que herdam um conjunto de métodos e atributos que veremos neste notebook.

Podemos criar um objeto ndarray com a função np.array() (além de diversas outras que veremos mais adiante). Para tanto, passamos uma lista ou iterável contendo os respectivos elementos como argumento desta função. Vejamos este processo na linha de código abaixo.

In [6]:
b = np.array([1, 2, 3, 4, 5])

Para verificar se o objeto criado é de fato um ndarray passamos o nome do array criado dentro da função built-in type():

In [4]:
type(b)

numpy.ndarray

Podemos verificar o tipo de dado associado ao objeto criado por meio do atributo *dtype*.

In [7]:
b.dtype

dtype('int64')

Para verificar o número de dimensões do array criado usamos o atributo *ndim*. O atributo *size* mostra o tamanho do array, enquanto que atributo shape evidencia a quantidade de elementos em cada dimensão do array.

In [6]:
b.ndim

1

In [7]:
b.shape

(5,)

In [8]:
b.size

5

O array b é unidimensional. Podemos criar um array de duas ou mais dimensões (como veremos mais adiante). Vejamos um exemplo:

In [11]:
k = np.array([[10.5, 1.3, 2], [4.3, 5.2, 1.8]])
print('Shape: ', k.shape)
print('Número de dimensões: ', k.ndim)
print('Tamanho: ', k.size)
print('Dtype: ', k.dtype)

Shape:  (2, 3)
Número de dimensões:  2
Tamanho:  6
Dtype:  float64


Para verificar o tamanho em bytes de cada elemento usamos o atributo *itemsize*. 

In [12]:
k.itemsize

8

Em síntes,o objeto ndarray possui como principais atributos:

<table border="1"  align="justify">
<tr>
    <td><h4>Atributo</h4></td>
  <td><h4>Descrição</h4></td>
</tr>

<tr>
  <td>shape</td>
  <td>Tupla que contém o número de elementos para cada dimensão do array.</td>
</tr>
<tr>
  <td>size</td>
  <td>Número total de elementos de um array.</td>
</tr>
<tr>
  <td>ndim</td>
  <td>Número de dimensões.</td>
</tr>
<tr>
  <td>nbytes</td>
  <td>Número de bytes utilizado para armazenar os dados.</td>
</tr>
<tr>
  <td>dtype</td>
  <td>Tipo de dado dos elementos presentes em um array.</td>
</tr>
</table>


## Tipos de dado

Anteriormente, vimos que o atributo dtype fornece o tipo de dado dos elementos de um determinado array. 

In [10]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

Outra possibilidade seria criar um array com strings.

In [8]:
c = np.array([['a', 'b'], ['c','d']])
c.dtype

dtype('<U1')

Podemos mudar o tipo de dado de um array passando o argumento dtype dentro da função np.array(). Checamos que array *a* possui elementos do tipo int. Vejamos como especificar explicitamente outro tipo de dado ao criar um array.

In [12]:
a = np.array([1,2,3], dtype=float)
a.dtype

dtype('float64')

Neste caso, nosso novo array *a* possui os mesmo números do exemplo anterior, não obstante seu tipo de dado seja float.
Por fim, o array *d* apresenta elementos do tipo *complex*.

In [15]:
d = np.array([[1,2,3],[4,5,6]], dtype=complex)
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

astype

Após criarmos um ndarray podemos converter seu tipo de dados com a função astype:

In [10]:
z = np.array([1, 2, 3])
z.dtype

dtype('int64')

In [19]:
z = z.astype(str, copy=True)

In [20]:
z.dtype

dtype('<U21')

## Criando diferentes tipos de arrays

Aprenderemos nesta subseção a utilizar diferentes funções do NumPy para criar arrays.

Criaremos um array de 2 dimensões (matriz) passando listas aninhadas como argumento da função np.array():

In [5]:
array1 = np.array([[4,5,6],[7,8,9],[1,0,1]])
array1

array([[4, 5, 6],
       [7, 8, 9],
       [1, 0, 1]])

Além de listas, podemos passar tuplas como argumento da função np.array().

In [6]:
array2 = np.array(((4,5,6),(7,8,9),(1,0,1)))
array2

array([[4, 5, 6],
       [7, 8, 9],
       [1, 0, 1]])

Podemos ainda passar simultaneamente listas e tuplas como argumento:

In [8]:
array3 = np.array([(1,2,3),[4,5,6]])
array3

array([[1, 2, 3],
       [4, 5, 6]])

A função np.zeros() permite criar um array contendo 0 em todas as suas entradas. Para tanto, passamos o *shape* do array como argumento da função.

In [23]:
zero = np.zeros(shape = (2,2))
zero

array([[0., 0.],
       [0., 0.]])

A função np.ones() cria um array contendo 1 em todas as suas entradas. Sua implementação é similar a função anterior.

In [26]:
i = np.ones(shape = (2,2))
i

array([[1., 1.],
       [1., 1.]])

O tipo de dado default desta função é float.No entanto, podemos passar o argumento dtype dentro da função *np.ones()* para alterar para um outro tipo.

In [28]:
i.dtype

dtype('float64')

In [31]:
i = np.ones(shape = (2,2), dtype=int)
i.dtype

dtype('int64')

Com a função *np.arange()* podemos criar uma sequência de números, construção similar a função built-in *range()* para números inteiros.

No exemplo abaixo criamos uma sequência de números inteiros entre 2010 e 2021. Mas, cabe observar que o primeiro o último número é $n-1$. Então, podemos pensar nesta função a partir da seguinte sintaxe: np.arange(start,end,step). O útlimo argumento (step) denota o espaçamento entre os valores. 

In [32]:
np.arange(2010,2021)

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

Se não especificarmos um valor de início, o valor default será o 0.

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

O exemplo abaixo cria uma sequência de números de 1 a 10 com espaçamento 2 (step).

In [38]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Para inverter uma sequência de números dentro do np.arange() podemos passar -1 como step.

In [39]:
np.arange(2020,2009,-1)

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010])

Neste exemplo, criamos uma sequência de números de 2010 a 2021 de 5 em 5.

In [22]:
np.arange(2010,2021,5)

array([2010, 2015, 2020])

Podemos utilizar np.arange() com a função reshape para criar um array de duas dimensões,isto é, transformar um array de uma dimensão em uma matriz.

In [25]:
np.arange(1,31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
np.arange(1,31).reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

Ou ainda,

In [41]:
np.arange(1,31).reshape(10,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [28]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

A função np.linspace() retorna um array com números com espaçamento uniforme em um intervalo definido.

Vamos criar um array com números dentro do intervalo [1,21] em 5 partes:

In [33]:
np.linspace(1,21,5)

array([ 1.,  6., 11., 16., 21.])

O NumPy possui diversas funções para gerar números aleatórios dentro do módulo np.random. Geraremos 10 números 
aleatórios entre 0 e 1 com a função random() deste módulo.

In [51]:
A = np.random.random(10)
A

array([0.45284293, 0.35297837, 0.65739946, 0.37035108, 0.45909298,
       0.71932412, 0.41299183, 0.90642327, 0.18045162, 0.74111887])

Podemos transformar esse vetor de uma dimensão em uma matriz com a função reshape.

In [52]:
A = A.reshape(5,2)
A

array([[0.45284293, 0.35297837],
       [0.65739946, 0.37035108],
       [0.45909298, 0.71932412],
       [0.41299183, 0.90642327],
       [0.18045162, 0.74111887]])

Com a funçã np.full() podemos criar arrays que serão totalmente preenchidos com um determinado valor.

In [54]:
np.full(shape = 10, fill_value = 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [53]:
np.full(shape = (5,5),fill_value = 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

Podemos criar também uma função identidade, com a função *np.eye()* ou ainda *np.identity()*. Passamos a ordem da matriz identidade como argumento.

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Operações

Nesta subseção aprenderemos a efetuar operações aritiméticas entre arrays. 

Definiremos dois arrays e em seguida efuaremos operações aritiméticas, elemento a elemento. Teremos como retorno outro array contendo o resultado da operação especificada.

In [62]:
a = np.array([10, 15, 20])
b = np.array([2, 5, 7])

Podemos somar 2 a cada número do array *a*:

In [45]:
a+2

array([12, 17, 22])

Ou subtrair 1 de cada elemento de *b*:

In [46]:
b-1

array([1, 4, 6])

Multiplicar ou dividir por escalar:

In [57]:
b*2

array([ 2,  4,  6,  8, 10])

In [58]:
b/2

array([0.5, 1. , 1.5, 2. , 2.5])

Obter a divisão inteira de um array por um escalar:

In [60]:
b//2

array([0, 1, 1, 2, 2])

Vejamos como efetuar operações elemento a elemento com *a* e *b*:

In [65]:
a+b

array([12, 20, 27])

In [66]:
a-b

array([ 8, 10, 13])

In [67]:
a*b

array([ 20,  75, 140])

In [68]:
a/b

array([5.        , 3.        , 2.85714286])

Poderíamos ter utilizado as funções np.add(), np.subtract(), np.multiply() e np.divide() para obter os mesmos resultados anteriores.

In [70]:
np.add(a,b)

array([12, 20, 27])

In [71]:
np.subtract(a,b)

array([ 8, 10, 13])

In [72]:
np.multiply(a,b)

array([ 20,  75, 140])

In [54]:
np.divide(a,b)

array([5.        , 3.        , 2.85714286])

Vamos elevar ao quadrado e cada elemento de *c* com a função *np.power()*. Em seguida obteremos a raiz quadrada de cada elemento deste vetor com a função *np.sqrt()*.

In [74]:
c = np.array([4,16, 25])

In [75]:
np.power(c, 2)

array([ 16, 256, 625])

In [76]:
np.sqrt(c)

array([2., 4., 5.])

Multiplicando os elementos do array *a* pela raiz quadrada dos elementos de *c*:

In [59]:
np.multiply(a,np.sqrt(c))

array([ 20.,  60., 100.])

Para arrays multidimensionais as operações aqui definidas continuam sendo efetuadas elemento por elemento.

In [78]:
a = np.full(shape = (3,3),fill_value = 5)
b = np.ones(shape = (3,3))

In [79]:
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [80]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.add(a,b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [83]:
np.subtract(a,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [85]:
np.divide(b,a)

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

In [86]:
np.multiply(a,b)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [88]:
a*b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

Assim, o operador * não efetua o produto matricial. Veremos mais adiante como utilizar esta biblioteca para calcular o produto entre matrizes.

## Comparação

Os operadores >,>=,<=,==,!= efetuam comparação elemento a elemento entre arrays.

In [3]:
a = np.ones(5)
b = np.full(shape=5,fill_value=1)
c = np.arange(5)

In [4]:
a

array([1., 1., 1., 1., 1.])

In [5]:
b

array([1, 1, 1, 1, 1])

In [6]:
c

array([0, 1, 2, 3, 4])

In [7]:
a == c  #verifica a igualdade entre os arrays elemento a elemento

array([False,  True, False, False, False])

In [9]:
a != c  #verifica a diferença elemento a elemento entre os arrays

array([ True, False,  True,  True,  True])

Para os demais operadores teremos a mesma validação (elemento a elemento):

In [11]:
c > a

array([False, False,  True,  True,  True])

In [12]:
c > 2  #comparação com um escalar

array([False, False, False,  True,  True])

In [13]:
a < c

array([False, False,  True,  True,  True])

In [14]:
c >= a

array([False,  True,  True,  True,  True])

In [15]:
c <= a

array([ True,  True, False, False, False])

## Incremento e decremento

Não há operadores específicos ++ ou -- para efetuar operações de incremento ou decremento. Para tal, podemos efetuar uma reatribuição de valores. Para incremento: array = array + scalar ou array+ = escalar. Para -, *, /, utilizamos sintaxe análoga.

In [17]:
ar = np.ones(10)
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
ar = ar+1  #incrementa cada valor com a unidade

In [19]:
ar

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [20]:
ar = ar-1  #decrementa cada valor em uma unidade

In [21]:
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
ar+=5  #equivale a ar = ar + 5

In [23]:
ar

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [24]:
ar-= 2  #equivale a ar = ar - 2

In [25]:
ar

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [31]:
ar/= 2  #ou ar = ar/2

In [28]:
ar

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [29]:
ar*=5  #ou ar = ar*5

In [30]:
ar

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

## Manipulando o shape

O NumPy possibilita modificar o shape de um array após sua criação. Há duas possibilidades de implementação. Transformaremos um array unidimensional com shape $(16,)$ em um array de duas dimensões com shape $(4,4)$.

In [32]:
w = np.arange(16)

In [34]:
w.shape

(16,)

In [35]:
w.shape = (4,4)

In [222]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Com a função reshape podemos fazer uma operação análoga a anterior, passando uma tupla com o novo shape do array.

In [38]:
a = np.arange(9)
a = a.reshape((3,3))

In [225]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Utilizaremos a função *ravel()* para efetuar a operação inversa a partir do array $a$, convertendo um array 2-D (duas dimensões) em 1-D.

In [39]:
a = a.ravel()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Outra manipulação possível é obter a transposta de um array. Tal operação não é válida para arrays 1-D.

In [46]:
w.shape = (16,)
w.shape

(16,)

In [48]:
w = w.T
w.shape

(16,)

Para uma matrix temos que:

In [51]:
a = np.array([[3,1],[4,2],[4,5]])
a.shape

(3, 2)

In [54]:
a = a.transpose()  #ou: a = a.T

In [53]:
a.shape

(2, 3)

## Indexação e fatimento

Nesta seção aprenderemos a selecionar elemento por meio do índice (indexing) e fatiamento (slicing).

A indexação do arrays NumPy é similar as listas do Python, em que cada elemento ocupa um determinado índice. No array o número 10 ocupa o índice 0, 15 possui índice 1 e assim sucessivamente. 

In [55]:
a = np.arange(10,30,5)
a

array([10, 15, 20, 25])

Então, para acessarmos um determinado elemento utilizamos *array[índice]*. Então, para acessar o número 10, que possui índice 0:

In [56]:
a[0]

10

Para os outros elementos:

In [57]:
a[1]

15

In [58]:
a[2]

20

Os arrays NumPy também suportam a indexação negativa, quando começamos a contar a partir do último elemento que possui índice -1 até o primeiro elemento do vetor. Em nosso exemplo, o número 25 possui índice -1, já o 20 índice -2, sucessivamente até o elemento 10 que possui índice -4.

In [59]:
a[-1]

25

In [60]:
a[-2]

20

In [61]:
a[-4]

10

Acessar múltiplos elementos por meio do índice:

In [139]:
array[[1,3]]

array([15, 25])

2-D arrays
* estrutura retangular de representação em linhas e colunas
* definido por dois eixos, onde 0 corresponde as linhas 1 as colunas
* a indexação é um par de valor (linha,coluna)
* array[linha,coluna]

In [145]:
matrix = np.arange(50,65).reshape(3,5)
matrix

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64]])

Para acessar o número 57:

In [146]:
matrix[1,2]

57

Fatiamento
* Extrair partes de um array ou gerar novos

In [148]:
array = np.arange(30,50)
array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [150]:
array[:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [151]:
array[1:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [155]:
array[:10]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [152]:
array[1:10]

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [153]:
array[::2]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [154]:
array[5:15:2]

array([35, 37, 39, 41, 43])

In [156]:
array[:10:5]

array([30, 35])

In [157]:
array[::]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

matrix[linha,coluna]

In [160]:
matrix = np.arange(10,30).reshape(10,2)
matrix

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

Selecionando a primeira linha

In [178]:
matrix[0,:]

array([10, 11])

Selecionar a primeira coluna

In [172]:
matrix[:,0].reshape(-1,1)

array([[10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28]])

Selecionar a segunda coluna

In [177]:
matrix[:,1].reshape(-1,1)

array([[11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23],
       [25],
       [27],
       [29]])

Extraindo uma parte da matriz temos que:

In [181]:
matrix[4:6,:]

array([[18, 19],
       [20, 21]])

In [182]:
matrix[[5,8],:]

array([[20, 21],
       [26, 27]])

In [184]:
matrix[[5,8],1].reshape(-1,1)

array([[21],
       [27]])

Selecionando elementos com condições e variávels booleanas

In [201]:
b = np.array([
    np.full(3,1),
    np.random.randint(15,20,size=3),
    np.arange(10,13)
])

In [205]:
b

array([[ 1,  1,  1],
       [19, 17, 15],
       [10, 11, 12]])

In [218]:
b<=1

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

O resultado é um array com valor booleano True ou False em suas respectivas entradas, evidenciando se a condição especificada é verdadeira ou não.

In [203]:
b[b<=1]

array([1, 1, 1])

In [207]:
b[b>=15].reshape(-1,1)

array([[19],
       [17],
       [15]])

In [209]:
b>15

array([[False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [213]:
k = np.random.random(size = (5,5))
k

array([[0.07704264, 0.74931919, 0.23730569, 0.92540303, 0.64228405],
       [0.16822529, 0.6771037 , 0.594721  , 0.10014934, 0.09071935],
       [0.79041427, 0.50175341, 0.44615312, 0.43616684, 0.51032312],
       [0.30894609, 0.74359186, 0.70094398, 0.24823855, 0.33080416],
       [0.01418367, 0.04728702, 0.44292195, 0.82922341, 0.8114826 ]])

In [214]:
k>0.5

array([[False,  True, False,  True,  True],
       [False,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [False,  True,  True, False, False],
       [False, False, False,  True,  True]])

In [217]:
k[k>0.5]

array([0.74931919, 0.92540303, 0.64228405, 0.6771037 , 0.594721  ,
       0.79041427, 0.50175341, 0.51032312, 0.74359186, 0.70094398,
       0.82922341, 0.8114826 ])

## Iterando em arrays

In [185]:
z = np.array([1,2,3,4,5])
for numero in z:
    print(numero)

1
2
3
4
5


In [186]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
for linha in matrix:
    print(linha)

[1 2 3]
[4 5 6]
[7 8 9]


In [187]:
for linha in matrix:
    for numero in linha:
        print(numero)

1
2
3
4
5
6
7
8
9


In [188]:
for numero in matrix.flat:
    print(numero)

1
2
3
4
5
6
7
8
9


In [190]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
np.apply_along_axis(func1d = np.mean, axis = 0, arr = matrix)

array([4., 5., 6.])

In [192]:
np.apply_along_axis(func1d = np.sum, axis = 0, arr = matrix)

array([12, 15, 18])

In [193]:
def exp(x):
    return x**2

np.apply_along_axis(func1d = exp, axis = 0, arr = matrix)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Aggregate Functions

Opera em um conjunto de valores e gera como output um único resultado numérico.

In [124]:
a = np.array([1,2,3])

In [125]:
a.sum()

6

In [127]:
a.min()

1

In [128]:
a.max()

3

In [129]:
a.mean()

2.0

In [132]:
a.std()

0.816496580927726

In [102]:
u = np.array([7, 10, 9, 8, 11, 11, 12])

In [116]:
def agreggate_summary(array):
    import numpy as np
    if isinstance(array,np.ndarray):
        print('Soma: ', np.sum(array))
        print('Valor mínimo: ', np.min(array))
        print('Valor máximo: ', np.max(array))
        print('Média: ', np.mean(array).round(2))
        print('Mediana: ', np.median(array))
        print('Desvio padrão: ', np.std(array).round(2))
    else:
        return None

In [117]:
agreggate_summary(u)

Soma:  68
Valor mínimo:  7
Valor máximo:  12
Média:  9.71
Mediana:  10.0
Desvio padrão:  1.67


In [118]:
agreggate_summary([1,2,3])

## Universal Functions(ufunc)

In [120]:
a = np.linspace(1,50,10)
a

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [121]:
np.sin(a)

array([ 0.84147098,  0.16056113, -0.62683289, -0.99851122, -0.70797672,
        0.05208808,  0.77760805,  0.98741822,  0.54237243, -0.26237485])

In [122]:
np.log(a)

array([0.        , 1.86321843, 2.47560426, 2.85263143, 3.1257854 ,
       3.34010969, 3.51650823, 3.6664066 , 3.79673685, 3.91202301])

In [123]:
b = np.array([4, 16, 25, 49])
np.sqrt(b)

array([2., 4., 5., 7.])

## Joining e splitting

In [233]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.full(shape = (2,4), fill_value = 5)

In [234]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [235]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 5, 5, 5],
       [5, 6, 7, 8, 5, 5, 5, 5]])

In [237]:
array1 = np.array([0,1,-1])
array2 = np.array([5,8,11])
array3 = np.array([17, 20, -2])

In [238]:
np.row_stack((array1, array2, array3))

array([[ 0,  1, -1],
       [ 5,  8, 11],
       [17, 20, -2]])

In [241]:
np.column_stack((array3, array2, array1))

array([[17,  5,  0],
       [20,  8,  1],
       [-2, 11, -1]])

* Dividir um array em partes

$C_{6 \times 10}$

In [244]:
C = np.arange(1,61).reshape(6,10)

In [245]:
C

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [255]:
[A,B] = np.hsplit(C,2)

Matrizes:
* $A_{6 \times 5}$
*$B_{6 \times 5}$

In [256]:
A.shape

(6, 5)

In [249]:
A

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [250]:
B

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30],
       [36, 37, 38, 39, 40],
       [46, 47, 48, 49, 50],
       [56, 57, 58, 59, 60]])

In [257]:
[E,F] = np.vsplit(C,2)

In [258]:
E

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [259]:
F

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

## Àlgebra Linear

In [69]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,1],[-1,2]])

In [70]:
a.dot(b)

array([[ 3,  5],
       [11, 11]])

In [71]:
np.dot(a,b)

array([[ 3,  5],
       [11, 11]])

O produto não segue a comutatividade.